import {
  ahidfFaq,
  ahidfPage,
  cgssFaq,
  cgssPage,
  cgtmseFaq,
  cgtmsePage,
  naifFaq,
  naifPage,
  pmegpFaq,
  pmegpPage,
  sisfsFaq,
  sisfsPage,
  ublFaq,
  ublPage,
  rdifFaq,
  rdifPage,
  sssFaq,
  sssPage,
  equityLinkedSeedFaq,
  equityLinkedSeedPage,
  evolveTechFaq,
  evolveTechPage,
  gvflFaq,
  gvflPage,
  horizonFundFaq,
  horizonFundPage,
  marineVentureFaq,
  marineVenturePage,
  matrixCapitalFaq,
  matrixCapitalPage,
  techEquityFaq,
  techEquityPage,
  udyogFundingFaq,
  udyogFundingPage,
  vcFundStFaq,
  vcFundStPage,
  ventureFundMahaFaq,
  ventureFundMahaPage,
  ventureFundingChallengeFaq,
  ventureFundingChallengePage,
  equityElevatorFaq,
  equityElevatorPage,
  deepTechFaq,
  deepTechPage,
  newVentureFaq,
  newVenturePage,
  ratanFundingFaq,
  ratanFundingPage,
  investmentReadinessFaq,
  investmentReadinessPage,
  technovibeFaq,
  technovibePage,
  ventureTechFaq,
  ventureTechPage,
  coldStorageSubsidyFaq,
  coldStorageSubsidyPage,
  pmKusumFaq,
  pmKusumPage,
  tweesFaq,
  tweesPage,
  semiconductorFaq,
  semiconductorPage,
  maharashtraGovtFaq,
  maharashtraGovtPage,
  mudraFaq,
  mudraPage,
  msmeLoanFaq,
  msmeLoanPage,
  standupFaq,
  standupPage,
  loanFaq,
  loanPage,
  nbfcFaq,
  nbfcPage,
  taxExemptionCertificateFaq,
  taxExemptionCertificatePage,
  actGrantFaq,
  actGrantPage,
  mahilaEmpowermentFaq,
  mahilaEmpowermentPage,
  sparkGrantFaq,
  sparkGrantPage,
  tide2Faq,
  tide2Page,
  rkvyRaftaarFaq,
  rkvyRaftaarPage,
  nidhiPrayasFaq,
  nidhiPrayasPage,
  meityGenesisEirFaq,
  meityGenesisEirPage,
  agriBusinessGrantsFaq,
  agriBusinessGrantsPage,
  socialImpactFaq,
  socialImpactPage,
  mobilityInnovationFaq,
  mobilityInnovationPage,
  greatSchemeFaq,
  greatSchemePage,
  uyegpFaq,
  uyegpPage,
  cybersecurityFundFaq,
  cybersecurityFundPage,
  artProgramFaq,
  artProgramPage,
  agriSureFundFaq,
  agriSureFundPage,
  grantForVenturesFaq,
  grantForVenturesPage,
  growthGrantFaq,
  growthGrantPage,
  brightpathVenturesFaq,
  brightpathVenturesPage,
  healthAcceleratorFaq,
  healthAcceleratorPage,
  startupAcceleratorFaq,
  startupAcceleratorPage,
  startupSparkFaq,
  startupSparkPage,
  leapFundSchemeFaq,
  leapFundSchemePage,
  hpUdgamFaq,
  hpUdgamPage,
  defenceSchemeFaq,
  defenceSchemePage,
  aditiDefenceFaq,
  aditiDefencePage,
  aerospaceDefenceFaq,
  aerospaceDefencePage,
  agriStartupShitijFaq,
  agriStartupShitijPage,
  agriTechFundFaq,
  agriTechFundPage,
  agrinextFaq,
  agrinextPage,
  lorealGreenFaq,
  lorealGreenPage,
  csrFundFaq,
  csrFundPage,
  cybersecurityKarnatakaFaq,
  cybersecurityKarnatakaPage,
  earlyStageGrantFaq,
  earlyStageGrantPage,
  elevateNxtFaq,
  elevateNxtPage,
  empowersphereFaq,
  empowerspherePage,
  fintechChallengeFaq,
  fintechChallengePage,
  fundScYouthFaq,
  fundScYouthPage,
  fundForUpFaq,
  fundForUpPage,
  startupIndiaEligibilityFaq,
  startupIndiaEligibilityPage,
  site,
} from "@/lib/content";
import { photos } from "@/lib/photos";
import { SCHEME_CANONICAL_ALIASES } from "@/lib/canonical-routes";
import type { ServiceDesk } from "@/lib/serviceDesks";

const desks: Record<string, ServiceDesk> = {
  naif: {
    title: `NAIF Scheme (AIF) | ${site.companyName}`,
    description:
      "Agriculture Infrastructure Fund (AIF / NAIF) — loans up to ₹2 Crore per project, 3% interest subvention for 7 years, and 100% CGTMSE cover for post-harvest agri infrastructure.",
    hero: {
      data: naifPage,
      images: {
        primary: photos.schemeAgri,
        secondary: photos.schemeHorticulture,
        circle: photos.schemeGuarantee,
        secondaryAlt: "Horticulture and cold-chain infrastructure for AIF",
        circleAlt: "CGTMSE credit guarantee documents for an AIF loan",
      },
      whatsappText:
        "Hi, I want to check eligibility for the NAIF / AIF scheme.",
    },
    unlock: {
      data: naifPage.unlock,
      image: {
        src: photos.schemeAgri,
        alt: "Agri infrastructure project under the Agriculture Infrastructure Fund",
      },
    },
    sections: [
      {
        type: "services",
        data: naifPage.benefits,
        sectionId: "naif-benefits",
      },
      {
        type: "categories",
        data: naifPage.eligibility,
        sectionId: "naif-eligibility",
      },
      { type: "process", data: naifPage.process, sectionId: "naif-process" },
      {
        type: "documents",
        data: naifPage.documents,
        sectionId: "naif-documents",
        whatsappText:
          "Hi, please send me the AIF / NAIF documents and DPR checklist.",
      },
    ],
    faq: naifFaq,
  },
  cgtmse: {
    title: `CGTMSE Loan Scheme | ${site.companyName}`,
    description:
      "CGTMSE collateral-free loans for micro and small enterprises — cover up to ₹500 Lakhs, 75–85% guarantee, and hybrid security through scheduled banks.",
    hero: {
      data: cgtmsePage,
      images: {
        primary: photos.schemeGuarantee,
        secondary: photos.serviceLoan,
        circle: photos.aboutServiceLoans,
        secondaryAlt: "MSME loan documents prepared for CGTMSE cover",
        circleAlt: "Founder reviewing a collateral-free credit file",
      },
      whatsappText: "Hi, I want to apply for a CGTMSE collateral-free loan.",
    },
    unlock: {
      data: cgtmsePage.unlock,
      image: {
        src: photos.schemeGuarantee,
        alt: "Credit guarantee papers for a CGTMSE MSME loan",
      },
    },
    sections: [
      {
        type: "services",
        data: cgtmsePage.features,
        sectionId: "cgtmse-features",
      },
      {
        type: "categories",
        data: cgtmsePage.benefits,
        sectionId: "cgtmse-benefits",
      },
      {
        type: "categories",
        data: cgtmsePage.focus,
        sectionId: "cgtmse-focus",
      },
      {
        type: "categories",
        data: cgtmsePage.eligibility,
        sectionId: "cgtmse-eligibility",
      },
      {
        type: "process",
        data: cgtmsePage.process,
        sectionId: "cgtmse-process",
      },
      {
        type: "documents",
        data: cgtmsePage.documents,
        sectionId: "cgtmse-documents",
        whatsappText:
          "Hi, please send me the CGTMSE loan documents checklist.",
      },
    ],
    faq: cgtmseFaq,
  },
  pmegp: {
    title: `PMEGP Scheme | ${site.companyName}`,
    description:
      "Prime Minister's Employment Generation Programme — up to 35% subsidy for new manufacturing and service units, implemented through KVIC, KVIBs and DICs.",
    hero: {
      data: pmegpPage,
      images: {
        primary: photos.schemePmegp,
        secondary: photos.schemeStandup,
        circle: photos.schemeGuarantee,
        secondaryAlt: "New manufacturing unit eligible for PMEGP subsidy",
        circleAlt: "Margin money and subsidy documents for PMEGP",
      },
      whatsappText: "Hi, I want to check eligibility for the PMEGP scheme.",
    },
    unlock: {
      data: pmegpPage.unlock,
      image: {
        src: photos.schemePmegp,
        alt: "Founder setting up a new unit under PMEGP",
      },
    },
    sections: [
      {
        type: "services",
        data: pmegpPage.benefits,
        sectionId: "pmegp-benefits",
      },
      {
        type: "categories",
        data: pmegpPage.eligibility,
        sectionId: "pmegp-eligibility",
      },
      { type: "process", data: pmegpPage.process, sectionId: "pmegp-process" },
      {
        type: "documents",
        data: pmegpPage.documents,
        sectionId: "pmegp-documents",
        whatsappText: "Hi, please send me the PMEGP documents checklist.",
      },
    ],
    faq: pmegpFaq,
  },
  ahidf: {
    title: `AHIDF Scheme | ${site.companyName}`,
    description:
      "Animal Husbandry Infrastructure Development Fund — up to 90% loan cover, 3% interest subvention for 8 years, and 25% NABARD guarantee for dairy, meat, feed and allied units.",
    hero: {
      data: ahidfPage,
      images: {
        primary: photos.schemeHorticulture,
        secondary: photos.schemeAgri,
        circle: photos.schemeGuarantee,
        secondaryAlt: "Agri and dairy infrastructure for AHIDF financing",
        circleAlt: "NABARD credit guarantee papers for an AHIDF loan",
      },
      whatsappText: "Hi, I want to check eligibility for the AHIDF scheme.",
    },
    unlock: {
      data: ahidfPage.unlock,
      image: {
        src: photos.schemeHorticulture,
        alt: "Animal husbandry infrastructure project under AHIDF",
      },
    },
    sections: [
      {
        type: "services",
        data: ahidfPage.benefits,
        sectionId: "ahidf-benefits",
      },
      {
        type: "categories",
        data: ahidfPage.eligibility,
        sectionId: "ahidf-eligibility",
      },
      { type: "process", data: ahidfPage.process, sectionId: "ahidf-process" },
      {
        type: "documents",
        data: ahidfPage.documents,
        sectionId: "ahidf-documents",
        whatsappText: "Hi, please send me the AHIDF documents checklist.",
      },
    ],
    faq: ahidfFaq,
  },
  cgss: {
    title: `CGSS Scheme | ${site.companyName}`,
    description:
      "Credit Guarantee Scheme for Startups — collateral-free loans up to ₹20 crore for DPIIT-recognised startups, with 85%/75% NCGTC cover and no equity dilution.",
    hero: {
      data: cgssPage,
      images: {
        primary: photos.schemeSeed,
        secondary: photos.schemeStartup,
        circle: photos.schemeGuarantee,
        secondaryAlt: "Startup team preparing a CGSS loan file",
        circleAlt: "NCGTC credit guarantee documents for CGSS",
      },
      whatsappText: "Hi, I want to apply for a CGSS startup loan.",
    },
    unlock: {
      data: cgssPage.unlock,
      image: {
        src: photos.schemeVc,
        alt: "Founder reviewing collateral-free CGSS debt options",
      },
    },
    sections: [
      {
        type: "services",
        data: cgssPage.benefits,
        sectionId: "cgss-benefits",
      },
      {
        type: "categories",
        data: cgssPage.features,
        sectionId: "cgss-features",
      },
      {
        type: "categories",
        data: cgssPage.focus,
        sectionId: "cgss-focus",
      },
      {
        type: "categories",
        data: cgssPage.eligibility,
        sectionId: "cgss-eligibility",
      },
      { type: "process", data: cgssPage.process, sectionId: "cgss-process" },
      {
        type: "documents",
        data: cgssPage.documents,
        sectionId: "cgss-documents",
        whatsappText: "Hi, please send me the CGSS loan documents checklist.",
      },
    ],
    faq: cgssFaq,
  },
  "seed-fund": {
    title: `Startup India Seed Fund (SISFS) | ${site.companyName}`,
    description:
      "Startup India Seed Fund Scheme — grants up to ₹20 lakh for PoC, prototype and trials, and up to ₹50 lakh as debt or convertible for market entry, via DPIIT incubators.",
    hero: {
      data: sisfsPage,
      images: {
        primary: photos.schemeSeed,
        secondary: photos.schemeStartup,
        circle: photos.schemePitch,
        secondaryAlt: "Startup team preparing a SISFS incubator application",
        circleAlt: "Founders reviewing a SISFS pitch and milestone plan",
      },
      whatsappText:
        "Hi, I want to check eligibility for the Startup India Seed Fund (SISFS).",
    },
    unlock: {
      data: sisfsPage.unlock,
      image: {
        src: photos.schemeSeed,
        alt: "Early-stage founders preparing a Startup India Seed Fund application",
      },
    },
    sections: [
      {
        type: "services",
        data: sisfsPage.whyChoose,
        sectionId: "sisfs-benefits",
      },
      {
        type: "categories",
        data: sisfsPage.eligibility,
        sectionId: "sisfs-eligibility",
      },
      { type: "process", data: sisfsPage.process, sectionId: "sisfs-process" },
      {
        type: "documents",
        data: sisfsPage.documents,
        sectionId: "sisfs-documents",
        whatsappText:
          "Hi, please send me the Startup India Seed Fund (SISFS) documents checklist.",
      },
    ],
    faq: sisfsFaq,
  },
  "unsecured-business-loan": {
    title: `Unsecured Business Loans | ${site.companyName}`,
    description:
      "Collateral-free unsecured business loans up to ₹50 Lakhs for MSMEs and startups — lender matching, documentation and fast approval without pledging assets.",
    hero: {
      data: ublPage,
      images: {
        primary: photos.serviceLoan,
        secondary: photos.aboutServiceLoans,
        circle: photos.schemeGuarantee,
        secondaryAlt: "Founder reviewing unsecured business loan options",
        circleAlt: "Credit and KYC documents for a collateral-free loan",
      },
      whatsappText:
        "Hi, I want to check eligibility for an unsecured business loan.",
    },
    unlock: {
      data: ublPage.unlock,
      image: {
        src: photos.serviceLoan,
        alt: "MSME owner preparing a collateral-free business loan application",
      },
    },
    sections: [
      {
        type: "services",
        data: ublPage.whyChoose,
        sectionId: "ubl-benefits",
      },
      {
        type: "categories",
        data: ublPage.eligibility,
        sectionId: "ubl-eligibility",
      },
      { type: "process", data: ublPage.process, sectionId: "ubl-process" },
      {
        type: "documents",
        data: ublPage.documents,
        sectionId: "ubl-documents",
        whatsappText:
          "Hi, please send me the unsecured business loan documents checklist.",
      },
    ],
    faq: ublFaq,
  },
  rdif: {
    title: `RDIF Scheme | ${site.companyName}`,
    description:
      "Research Development and Innovation Fund (RDIF) — up to 50% project cost cover, concessional 3–4% interest, and 12–15 year tenure for deep-tech and strategic R&D via DST/TDB.",
    hero: {
      data: rdifPage,
      images: {
        primary: photos.schemeLab,
        secondary: photos.schemeStartup,
        circle: photos.schemePitch,
        secondaryAlt: "Startup team preparing an RDIF R&D proposal",
        circleAlt: "Founders reviewing TRL and DPR documents for RDIF",
      },
      whatsappText: "Hi, I want to check eligibility for the RDIF Scheme.",
    },
    unlock: {
      data: rdifPage.unlock,
      image: {
        src: photos.schemeLab,
        alt: "Lab and deep-tech R&D work eligible for RDIF funding",
      },
    },
    sections: [
      {
        type: "services",
        data: rdifPage.benefits,
        sectionId: "rdif-benefits",
      },
      {
        type: "categories",
        data: rdifPage.eligibility,
        sectionId: "rdif-eligibility",
      },
      {
        type: "categories",
        data: rdifPage.focus,
        sectionId: "rdif-focus",
      },
      {
        type: "categories",
        data: rdifPage.funding,
        sectionId: "rdif-funding",
      },
      { type: "process", data: rdifPage.process, sectionId: "rdif-process" },
      {
        type: "documents",
        data: rdifPage.documents,
        sectionId: "rdif-documents",
        whatsappText: "Hi, please send me the RDIF documents and DPR checklist.",
      },
    ],
    faq: rdifFaq,
  },
  sss: {
    title: `Startup Support Scheme (SSS) | ${site.companyName}`,
    description:
      "Startup Support Scheme (SSS) — equity, debt or equity-linked funding from ₹25 lakh to ₹1 crore for DPIIT-recognised tech startups, with mentorship and growth support.",
    hero: {
      data: sssPage,
      images: {
        primary: photos.schemeStartup,
        secondary: photos.schemePitch,
        circle: photos.schemeSeed,
        secondaryAlt: "Founders pitching for Startup Support Scheme funding",
        circleAlt: "Early-stage startup preparing an SSS equity file",
      },
      whatsappText:
        "Hi, I want to check eligibility for the Startup Support Scheme (SSS).",
    },
    unlock: {
      data: sssPage.unlock,
      image: {
        src: photos.schemeStartup,
        alt: "Technology startup team exploring SSS equity funding",
      },
    },
    sections: [
      {
        type: "services",
        data: sssPage.benefits,
        sectionId: "sss-benefits",
      },
      {
        type: "categories",
        data: sssPage.eligibility,
        sectionId: "sss-eligibility",
      },
      { type: "process", data: sssPage.process, sectionId: "sss-process" },
      {
        type: "documents",
        data: sssPage.documents,
        sectionId: "sss-documents",
        whatsappText:
          "Hi, please send me the Startup Support Scheme (SSS) documents checklist.",
      },
    ],
    faq: sssFaq,
  },
  "equity-linked-seed": {
    title: `Equity Linked Seed Fund | ${site.companyName}`,
    description:
      "Equity Linked Seed Fund — up to ₹30 lakh grant/equity-linked support, capped ~10% stake, and pre-Series A pathways for DPIIT-recognised innovative startups.",
    hero: {
      data: equityLinkedSeedPage,
      images: {
        primary: photos.schemeSeed,
        secondary: photos.schemePitch,
        circle: photos.schemeStartup,
        secondaryAlt: "Founders pitching for Equity Linked Seed Fund support",
        circleAlt: "Startup team reviewing an equity-linked seed file",
      },
      whatsappText:
        "Hi, I want to check eligibility for the Equity Linked Seed Fund.",
    },
    unlock: {
      data: equityLinkedSeedPage.unlock,
      image: {
        src: photos.schemeSeed,
        alt: "Early-stage founders preparing an Equity Linked Seed Fund application",
      },
    },
    sections: [
      {
        type: "services",
        data: equityLinkedSeedPage.benefits,
        sectionId: "els-benefits",
      },
      {
        type: "categories",
        data: equityLinkedSeedPage.objectives,
        sectionId: "els-objectives",
      },
      {
        type: "categories",
        data: equityLinkedSeedPage.focus,
        sectionId: "els-focus",
      },
      {
        type: "categories",
        data: equityLinkedSeedPage.eligibility,
        sectionId: "els-eligibility",
      },
      {
        type: "process",
        data: equityLinkedSeedPage.process,
        sectionId: "els-process",
      },
      {
        type: "documents",
        data: equityLinkedSeedPage.documents,
        sectionId: "els-documents",
        whatsappText:
          "Hi, please send me the Equity Linked Seed Fund documents checklist.",
      },
    ],
    faq: equityLinkedSeedFaq,
  },
  "horizon-fund": {
    title: `Horizon Fund | ${site.companyName}`,
    description:
      "Horizon Fund equity investment for revenue-generating growth-stage startups, with initial and follow-up capital, mentorship and investor access.",
    hero: {
      data: horizonFundPage,
      images: { primary: photos.schemeVc, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Horizon Fund startup pitch", circleAlt: "Growth-stage startup team" },
      whatsappText: "Hi, I want to check eligibility for the Horizon Fund.",
    },
    unlock: { data: horizonFundPage.unlock, image: { src: photos.schemeVc, alt: "Horizon Fund growth-stage investment" } },
    sections: [
      { type: "services", data: horizonFundPage.benefits, sectionId: "horizon-benefits" },
      { type: "categories", data: horizonFundPage.eligibility, sectionId: "horizon-eligibility" },
      { type: "process", data: horizonFundPage.process, sectionId: "horizon-process" },
      { type: "documents", data: horizonFundPage.documents, sectionId: "horizon-documents", whatsappText: "Hi, please send me the Horizon Fund documents checklist." },
    ],
    faq: horizonFundFaq,
  },
  gvfl: {
    title: `GVFL Scheme | ${site.companyName}`,
    description: "GVFL equity and quasi-equity support for innovative, growth-stage businesses with scalable execution plans.",
    hero: {
      data: gvflPage,
      images: { primary: photos.credentialGrowth, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "GVFL investment pitch", circleAlt: "GVFL startup founders" },
      whatsappText: "Hi, I want to check eligibility for GVFL funding.",
    },
    unlock: { data: gvflPage.unlock, image: { src: photos.credentialGrowth, alt: "GVFL equity funding support" } },
    sections: [
      { type: "services", data: gvflPage.benefits, sectionId: "gvfl-benefits" },
      { type: "categories", data: gvflPage.eligibility, sectionId: "gvfl-eligibility" },
      { type: "process", data: gvflPage.process, sectionId: "gvfl-process" },
      { type: "documents", data: gvflPage.documents, sectionId: "gvfl-documents", whatsappText: "Hi, please send me the GVFL documents checklist." },
    ],
    faq: gvflFaq,
  },
  "evolve-tech": {
    title: `Evolve-Tech Funding 2.0 | ${site.companyName}`,
    description: "Evolve-Tech Funding 2.0 offers seed equity capital, mentorship and investor-readiness support for MVP-stage technology startups.",
    hero: {
      data: evolveTechPage,
      images: { primary: photos.schemeStartup, secondary: photos.schemePitch, circle: photos.schemeSeed, secondaryAlt: "Evolve-Tech investor pitch", circleAlt: "Technology startup founders" },
      whatsappText: "Hi, I want to check eligibility for Evolve-Tech Funding 2.0.",
    },
    unlock: { data: evolveTechPage.unlock, image: { src: photos.schemeStartup, alt: "Evolve-Tech startup funding" } },
    sections: [
      { type: "services", data: evolveTechPage.benefits, sectionId: "evolve-tech-benefits" },
      { type: "categories", data: evolveTechPage.eligibility, sectionId: "evolve-tech-eligibility" },
      { type: "process", data: evolveTechPage.process, sectionId: "evolve-tech-process" },
      { type: "documents", data: evolveTechPage.documents, sectionId: "evolve-tech-documents", whatsappText: "Hi, please send me the Evolve-Tech Funding documents checklist." },
    ],
    faq: evolveTechFaq,
  },
  "venture-tech": {
    title: `Venture Tech Funding | ${site.companyName}`,
    description: "Chiratae Sonic Venture Tech Funding for early-stage disruptive tech startups with seed capital up to ₹18 crore.",
    hero: {
      data: ventureTechPage,
      images: { primary: photos.schemeLab, secondary: photos.schemePitch, circle: photos.schemeTech, secondaryAlt: "Venture Tech Funding founder pitch", circleAlt: "Disruptive tech startup team" },
      whatsappText: "Hi, I want to check eligibility for Venture Tech Funding.",
    },
    unlock: { data: ventureTechPage.unlock, image: { src: photos.schemeLab, alt: "Venture Tech Funding Chiratae Sonic support" } },
    sections: [
      { type: "services", data: ventureTechPage.benefits, sectionId: "venture-tech-benefits" },
      { type: "categories", data: ventureTechPage.eligibility, sectionId: "venture-tech-eligibility" },
      { type: "process", data: ventureTechPage.process, sectionId: "venture-tech-process" },
      { type: "documents", data: ventureTechPage.documents, sectionId: "venture-tech-documents", whatsappText: "Hi, please send me the Venture Tech Funding documents checklist." },
    ],
    faq: ventureTechFaq,
  },
  "marine-venture": {
    title: `Marine Venture | ${site.companyName}`,
    description: "Marine Venture provides equity-led capital, incubation and specialist mentorship for maritime, shipping and ocean-tech startups.",
    hero: {
      data: marineVenturePage,
      images: { primary: photos.schemeMarine, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Marine Venture maritime technology pitch", circleAlt: "Ocean-tech startup team" },
      whatsappText: "Hi, I want to check eligibility for Marine Venture.",
    },
    unlock: { data: marineVenturePage.unlock, image: { src: photos.schemeMarine, alt: "Marine Venture maritime startup support" } },
    sections: [
      { type: "services", data: marineVenturePage.benefits, sectionId: "marine-benefits" },
      { type: "categories", data: marineVenturePage.eligibility, sectionId: "marine-eligibility" },
      { type: "process", data: marineVenturePage.process, sectionId: "marine-process" },
      { type: "documents", data: marineVenturePage.documents, sectionId: "marine-documents", whatsappText: "Hi, please send me the Marine Venture documents checklist." },
    ],
    faq: marineVentureFaq,
  },
  "matrix-capital": {
    title: `Matrix Capital Fellowship | ${site.companyName}`,
    description: "Matrix Capital Fellowship offers ambitious global technology founders capital pathways, elite mentorship and investor exposure.",
    hero: {
      data: matrixCapitalPage,
      images: { primary: photos.aboutTeam, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Matrix Capital Fellowship founder pitch", circleAlt: "Global technology founders" },
      whatsappText: "Hi, I want to check eligibility for the Matrix Capital Fellowship.",
    },
    unlock: { data: matrixCapitalPage.unlock, image: { src: photos.aboutTeam, alt: "Matrix Capital Fellowship founder mentorship" } },
    sections: [
      { type: "services", data: matrixCapitalPage.benefits, sectionId: "matrix-benefits" },
      { type: "categories", data: matrixCapitalPage.eligibility, sectionId: "matrix-eligibility" },
      { type: "process", data: matrixCapitalPage.process, sectionId: "matrix-process" },
      { type: "documents", data: matrixCapitalPage.documents, sectionId: "matrix-documents", whatsappText: "Hi, please send me the Matrix Capital Fellowship documents checklist." },
    ],
    faq: matrixCapitalFaq,
  },
  "tech-equity": {
    title: `Tech Equity Program | ${site.companyName}`,
    description: "Global acceleration, funding and mentorship for early-stage Web3, blockchain and AI startups.",
    hero: { data: techEquityPage, images: { primary: photos.schemeLab, secondary: photos.schemePitch, circle: photos.schemeTech, secondaryAlt: "Tech Equity Program founder pitch", circleAlt: "Web3 startup team" }, whatsappText: "Hi, I want to check eligibility for the Tech Equity Program." },
    unlock: { data: techEquityPage.unlock, image: { src: photos.schemeLab, alt: "Tech Equity Program startup accelerator" } },
    sections: [{ type: "services", data: techEquityPage.benefits, sectionId: "tech-equity-benefits" }, { type: "categories", data: techEquityPage.eligibility, sectionId: "tech-equity-eligibility" }, { type: "process", data: techEquityPage.process, sectionId: "tech-equity-process" }, { type: "documents", data: techEquityPage.documents, sectionId: "tech-equity-documents", whatsappText: "Hi, please send me the Tech Equity Program documents checklist." }],
    faq: techEquityFaq,
  },
  "udyog-funding": {
    title: `Udyog Funding | ${site.companyName}`,
    description: "Global startup competition and SAFE investment pathway for founders pursuing international growth.",
    hero: { data: udyogFundingPage, images: { primary: photos.serviceGrowth, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Udyog Funding global pitch", circleAlt: "Global startup founders" }, whatsappText: "Hi, I want to check eligibility for Udyog Funding." },
    unlock: { data: udyogFundingPage.unlock, image: { src: photos.serviceGrowth, alt: "Udyog Funding global startup competition" } },
    sections: [{ type: "services", data: udyogFundingPage.benefits, sectionId: "udyog-benefits" }, { type: "categories", data: udyogFundingPage.eligibility, sectionId: "udyog-eligibility" }, { type: "process", data: udyogFundingPage.process, sectionId: "udyog-process" }, { type: "documents", data: udyogFundingPage.documents, sectionId: "udyog-documents", whatsappText: "Hi, please send me the Udyog Funding documents checklist." }],
    faq: udyogFundingFaq,
  },
  "vc-fund-st": {
    title: `VC Fund for ST | ${site.companyName}`,
    description: "Institutional capital and incubation support for eligible Scheduled Tribe entrepreneurs.",
    hero: { data: vcFundStPage, images: { primary: photos.schemeStandup, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "VC Fund for ST investment pitch", circleAlt: "ST entrepreneur startup team" }, whatsappText: "Hi, I want to check eligibility for VC Fund for ST." },
    unlock: { data: vcFundStPage.unlock, image: { src: photos.schemeStandup, alt: "VC Fund for ST entrepreneur support" } },
    sections: [{ type: "services", data: vcFundStPage.benefits, sectionId: "vc-st-benefits" }, { type: "categories", data: vcFundStPage.eligibility, sectionId: "vc-st-eligibility" }, { type: "process", data: vcFundStPage.process, sectionId: "vc-st-process" }, { type: "documents", data: vcFundStPage.documents, sectionId: "vc-st-documents", whatsappText: "Hi, please send me the VC Fund for ST documents checklist." }],
    faq: vcFundStFaq,
  },
  "venture-fund": {
    title: `Venture Fund (MH) | ${site.companyName}`,
    description: "Maharashtra equity funding and institutional guidance for eligible innovation-led startups.",
    hero: { data: ventureFundMahaPage, images: { primary: photos.schemeVc, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Maharashtra Venture Fund pitch", circleAlt: "Maharashtra startup team" }, whatsappText: "Hi, I want to check eligibility for Venture Fund (MH)." },
    unlock: { data: ventureFundMahaPage.unlock, image: { src: photos.schemeVc, alt: "Maharashtra Venture Fund startup support" } },
    sections: [{ type: "services", data: ventureFundMahaPage.benefits, sectionId: "venture-mh-benefits" }, { type: "categories", data: ventureFundMahaPage.eligibility, sectionId: "venture-mh-eligibility" }, { type: "process", data: ventureFundMahaPage.process, sectionId: "venture-mh-process" }, { type: "documents", data: ventureFundMahaPage.documents, sectionId: "venture-mh-documents", whatsappText: "Hi, please send me the Venture Fund documents checklist." }],
    faq: ventureFundMahaFaq,
  },
  "venture-challenge": {
    title: `Venture Funding Challenge | ${site.companyName}`,
    description: "Seed capital and hybrid incubation by Shiv Nadar AIC for innovation-led Indian startups.",
    hero: { data: ventureFundingChallengePage, images: { primary: photos.credentialGrowth, secondary: photos.schemePitch, circle: photos.schemeLab, secondaryAlt: "Venture Funding Challenge pitch", circleAlt: "Incubation programme founders" }, whatsappText: "Hi, I want to check eligibility for the Venture Funding Challenge." },
    unlock: { data: ventureFundingChallengePage.unlock, image: { src: photos.credentialGrowth, alt: "Venture Funding Challenge incubation support" } },
    sections: [{ type: "services", data: ventureFundingChallengePage.benefits, sectionId: "venture-challenge-benefits" }, { type: "categories", data: ventureFundingChallengePage.eligibility, sectionId: "venture-challenge-eligibility" }, { type: "process", data: ventureFundingChallengePage.process, sectionId: "venture-challenge-process" }, { type: "documents", data: ventureFundingChallengePage.documents, sectionId: "venture-challenge-documents", whatsappText: "Hi, please send me the Venture Funding Challenge documents checklist." }],
    faq: ventureFundingChallengeFaq,
  },
  "equity-elevator": {
    title: `Equity Elevator | ${site.companyName}`,
    description: "International equity funding up to ₹4 crore with Silicon Valley mentorship for tech startups.",
    hero: { data: equityElevatorPage, images: { primary: photos.schemePitch, secondary: photos.schemeStartup, circle: photos.schemeLab, secondaryAlt: "Equity Elevator founder mentorship", circleAlt: "Tech startup acceleration team" }, whatsappText: "Hi, I want to check eligibility for Equity Elevator." },
    unlock: { data: equityElevatorPage.unlock, image: { src: photos.schemePitch, alt: "Equity Elevator international funding" } },
    sections: [{ type: "services", data: equityElevatorPage.benefits, sectionId: "equity-elevator-benefits" }, { type: "categories", data: equityElevatorPage.eligibility, sectionId: "equity-elevator-eligibility" }, { type: "process", data: equityElevatorPage.process, sectionId: "equity-elevator-process" }, { type: "documents", data: equityElevatorPage.documents, sectionId: "equity-elevator-documents", whatsappText: "Hi, please send me the Equity Elevator documents checklist." }],
    faq: equityElevatorFaq,
  },
  "deep-tech": {
    title: `Deep Tech Funding | ${site.companyName}`,
    description: "IIT Tirupati TIH deep-tech grant support up to ₹1 crore for academia–startup collaborations.",
    hero: { data: deepTechPage, images: { primary: photos.schemeLab, secondary: photos.schemeTech, circle: photos.schemeStartup, secondaryAlt: "Deep tech research collaboration", circleAlt: "Early-stage deep-tech founders" }, whatsappText: "Hi, I want to check eligibility for Deep Tech Funding." },
    unlock: { data: deepTechPage.unlock, image: { src: photos.schemeLab, alt: "Deep Tech Funding research support" } },
    sections: [{ type: "services", data: deepTechPage.benefits, sectionId: "deep-tech-benefits" }, { type: "categories", data: deepTechPage.eligibility, sectionId: "deep-tech-eligibility" }, { type: "process", data: deepTechPage.process, sectionId: "deep-tech-process" }, { type: "documents", data: deepTechPage.documents, sectionId: "deep-tech-documents", whatsappText: "Hi, please send me the Deep Tech Funding documents checklist." }],
    faq: deepTechFaq,
  },
  "new-venture": {
    title: `New Venture Program | ${site.companyName}`,
    description: "EmTek Industry 4.0 New Venture Program with funding, lab access and mentorship up to ₹30 lakh.",
    hero: { data: newVenturePage, images: { primary: photos.schemeStartup, secondary: photos.schemePitch, circle: photos.schemeLab, secondaryAlt: "New Venture Program pitch", circleAlt: "Industry 4.0 startup team" }, whatsappText: "Hi, I want to check eligibility for the New Venture Program." },
    unlock: { data: newVenturePage.unlock, image: { src: photos.schemeStartup, alt: "New Venture Program Industry 4.0 support" } },
    sections: [{ type: "services", data: newVenturePage.benefits, sectionId: "new-venture-benefits" }, { type: "categories", data: newVenturePage.eligibility, sectionId: "new-venture-eligibility" }, { type: "process", data: newVenturePage.process, sectionId: "new-venture-process" }, { type: "documents", data: newVenturePage.documents, sectionId: "new-venture-documents", whatsappText: "Hi, please send me the New Venture Program documents checklist." }],
    faq: newVentureFaq,
  },
  "ratan-funding": {
    title: `Ratan Funding | ${site.companyName}`,
    description: "Ratan Tata Innovation Hub seed support up to ₹30 lakh for validated prototype startups.",
    hero: { data: ratanFundingPage, images: { primary: photos.schemePitch, secondary: photos.schemeStartup, circle: photos.schemeSeed, secondaryAlt: "Ratan Funding founder pitch", circleAlt: "Early-stage startup founders" }, whatsappText: "Hi, I want to check eligibility for Ratan Funding." },
    unlock: { data: ratanFundingPage.unlock, image: { src: photos.schemePitch, alt: "Ratan Funding seed support" } },
    sections: [{ type: "services", data: ratanFundingPage.benefits, sectionId: "ratan-benefits" }, { type: "categories", data: ratanFundingPage.eligibility, sectionId: "ratan-eligibility" }, { type: "process", data: ratanFundingPage.process, sectionId: "ratan-process" }, { type: "documents", data: ratanFundingPage.documents, sectionId: "ratan-documents", whatsappText: "Hi, please send me the Ratan Funding documents checklist." }],
    faq: ratanFundingFaq,
  },
  "investment-readiness": {
    title: `Investment Readiness Accelerator (IRA) 2.0 | ${site.companyName}`,
    description: "ISB I-Venture IRA 2.0 prepares Seed to Series A startups for investor meetings and fundraising.",
    hero: { data: investmentReadinessPage, images: { primary: photos.schemeVc, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Investment readiness pitch coaching", circleAlt: "Founders preparing for Demo Day" }, whatsappText: "Hi, I want to check eligibility for IRA 2.0." },
    unlock: { data: investmentReadinessPage.unlock, image: { src: photos.schemeVc, alt: "Investment Readiness Accelerator support" } },
    sections: [{ type: "services", data: investmentReadinessPage.benefits, sectionId: "ira-benefits" }, { type: "categories", data: investmentReadinessPage.eligibility, sectionId: "ira-eligibility" }, { type: "process", data: investmentReadinessPage.process, sectionId: "ira-process" }, { type: "documents", data: investmentReadinessPage.documents, sectionId: "ira-documents", whatsappText: "Hi, please send me the IRA 2.0 documents checklist." }],
    faq: investmentReadinessFaq,
  },
  technovibe: {
    title: `TechnoVibe Funding | ${site.companyName}`,
    description: "Tiered blockchain grants up to ₹10 lakh for governance, supply chain and healthcare solutions.",
    hero: { data: technovibePage, images: { primary: photos.schemeTech, secondary: photos.schemeLab, circle: photos.schemeStartup, secondaryAlt: "Blockchain startup technical review", circleAlt: "TechnoVibe founder team" }, whatsappText: "Hi, I want to check eligibility for TechnoVibe Funding." },
    unlock: { data: technovibePage.unlock, image: { src: photos.schemeTech, alt: "TechnoVibe blockchain funding" } },
    sections: [{ type: "services", data: technovibePage.benefits, sectionId: "technovibe-benefits" }, { type: "categories", data: technovibePage.eligibility, sectionId: "technovibe-eligibility" }, { type: "process", data: technovibePage.process, sectionId: "technovibe-process" }, { type: "documents", data: technovibePage.documents, sectionId: "technovibe-documents", whatsappText: "Hi, please send me the TechnoVibe documents checklist." }],
    faq: technovibeFaq,
  },
  "cold-storage-subsidy": {
    title: `Cold Storage Subsidy Scheme | ${site.companyName}`,
    description: "NHB/MIDH capital subsidy and interest support for multi-chamber cold storage projects from 251 MT to 20,000 MT.",
    hero: {
      data: coldStorageSubsidyPage,
      images: { primary: photos.schemeHorticulture, secondary: photos.schemeAgri, circle: photos.schemeGuarantee, secondaryAlt: "Cold storage agro infrastructure", circleAlt: "Horticulture cold chain facility" },
      whatsappText: "Hi, I want to check eligibility for the Cold Storage Subsidy Scheme.",
    },
    unlock: { data: coldStorageSubsidyPage.unlock, image: { src: photos.schemeHorticulture, alt: "Cold Storage Subsidy Scheme support" } },
    sections: [
      { type: "services", data: coldStorageSubsidyPage.benefits, sectionId: "cold-storage-benefits" },
      { type: "categories", data: coldStorageSubsidyPage.eligibility, sectionId: "cold-storage-eligibility" },
      { type: "process", data: coldStorageSubsidyPage.process, sectionId: "cold-storage-process" },
      { type: "documents", data: coldStorageSubsidyPage.documents, sectionId: "cold-storage-documents", whatsappText: "Hi, please send me the Cold Storage Subsidy documents checklist." },
    ],
    faq: coldStorageSubsidyFaq,
  },
  "pm-kusum": {
    title: `PM KUSUM Scheme | ${site.companyName}`,
    description: "Solar pumps, decentralised plants and grid solarisation with subsidy support up to 60–80% for eligible farmers.",
    hero: {
      data: pmKusumPage,
      images: { primary: photos.schemeSolar, secondary: photos.schemeAgri, circle: photos.schemeHorticulture, secondaryAlt: "Solar agricultural pump installation", circleAlt: "Farmers using solar irrigation" },
      whatsappText: "Hi, I want to check eligibility for the PM KUSUM Scheme.",
    },
    unlock: { data: pmKusumPage.unlock, image: { src: photos.schemeSolar, alt: "PM KUSUM solar agriculture support" } },
    sections: [
      { type: "services", data: pmKusumPage.benefits, sectionId: "pm-kusum-benefits" },
      { type: "categories", data: pmKusumPage.eligibility, sectionId: "pm-kusum-eligibility" },
      { type: "process", data: pmKusumPage.process, sectionId: "pm-kusum-process" },
      { type: "documents", data: pmKusumPage.documents, sectionId: "pm-kusum-documents", whatsappText: "Hi, please send me the PM KUSUM documents checklist." },
    ],
    faq: pmKusumFaq,
  },
  twees: {
    title: `TWEES Scheme | ${site.companyName}`,
    description: "Tamil Nadu Women Employment and Entrepreneurship Scheme — loans up to ₹10 lakh with 25% subsidy.",
    hero: {
      data: tweesPage,
      images: { primary: photos.schemeStandup, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Women entrepreneur business planning", circleAlt: "TWEES scheme applicants" },
      whatsappText: "Hi, I want to check eligibility for the TWEES Scheme.",
    },
    unlock: { data: tweesPage.unlock, image: { src: photos.schemeStandup, alt: "TWEES Scheme women entrepreneurship support" } },
    sections: [
      { type: "services", data: tweesPage.benefits, sectionId: "twees-benefits" },
      { type: "categories", data: tweesPage.eligibility, sectionId: "twees-eligibility" },
      { type: "process", data: tweesPage.process, sectionId: "twees-process" },
      { type: "documents", data: tweesPage.documents, sectionId: "twees-documents", whatsappText: "Hi, please send me the TWEES documents checklist." },
    ],
    faq: tweesFaq,
  },
  semiconductor: {
    title: `Semiconductor Scheme | ${site.companyName}`,
    description: "India Semiconductor Mission incentives for fabs, packaging, design-linked support and deep-tech accelerators.",
    hero: {
      data: semiconductorPage,
      images: { primary: photos.schemeTech, secondary: photos.schemeLab, circle: photos.schemeStartup, secondaryAlt: "Semiconductor design and manufacturing", circleAlt: "Deep-tech chip innovation team" },
      whatsappText: "Hi, I want to check eligibility for the Semiconductor Scheme.",
    },
    unlock: { data: semiconductorPage.unlock, image: { src: photos.schemeTech, alt: "Semiconductor Scheme incentive support" } },
    sections: [
      { type: "services", data: semiconductorPage.benefits, sectionId: "semiconductor-benefits" },
      { type: "categories", data: semiconductorPage.eligibility, sectionId: "semiconductor-eligibility" },
      { type: "process", data: semiconductorPage.process, sectionId: "semiconductor-process" },
      { type: "documents", data: semiconductorPage.documents, sectionId: "semiconductor-documents", whatsappText: "Hi, please send me the Semiconductor Scheme documents checklist." },
    ],
    faq: semiconductorFaq,
  },
  "maharashtra-govt": {
    title: `Maharashtra Government Schemes | ${site.companyName}`,
    description: "State-backed grants, equity and loan pathways including Agri-Sure, Startup Agro, Venture Fund (MH) and cluster support.",
    hero: {
      data: maharashtraGovtPage,
      images: { primary: photos.footerCity, secondary: photos.schemePitch, circle: photos.schemeStartup, secondaryAlt: "Maharashtra startup funding pitch", circleAlt: "Maharashtra MSME founders" },
      whatsappText: "Hi, I want to check eligibility for Maharashtra Government Schemes.",
    },
    unlock: { data: maharashtraGovtPage.unlock, image: { src: photos.footerCity, alt: "Maharashtra Government Schemes support" } },
    sections: [
      { type: "services", data: maharashtraGovtPage.benefits, sectionId: "mh-govt-benefits" },
      { type: "categories", data: maharashtraGovtPage.eligibility, sectionId: "mh-govt-eligibility" },
      { type: "process", data: maharashtraGovtPage.process, sectionId: "mh-govt-process" },
      { type: "documents", data: maharashtraGovtPage.documents, sectionId: "mh-govt-documents", whatsappText: "Hi, please send me the Maharashtra Government Schemes documents checklist." },
    ],
    faq: maharashtraGovtFaq,
  },
  mudra: {
    title: `Mudra Loans (PMMY) | ${site.companyName}`,
    description: "Pradhan Mantri Mudra Yojana — collateral-free micro loans up to ₹20 lakh across Shishu, Kishore and Tarun.",
    hero: {
      data: mudraPage,
      images: { primary: photos.schemeMudra, secondary: photos.serviceLoan, circle: photos.schemeStandup, secondaryAlt: "Micro enterprise Mudra loan documentation", circleAlt: "Small business owner receiving Mudra credit" },
      whatsappText: "Hi, I want to check eligibility for a Mudra loan.",
    },
    unlock: { data: mudraPage.unlock, image: { src: photos.schemeMudra, alt: "Mudra loan support for micro enterprises" } },
    sections: [
      { type: "services", data: mudraPage.benefits, sectionId: "mudra-benefits" },
      { type: "categories", data: mudraPage.eligibility, sectionId: "mudra-eligibility" },
      { type: "process", data: mudraPage.process, sectionId: "mudra-process" },
      { type: "documents", data: mudraPage.documents, sectionId: "mudra-documents", whatsappText: "Hi, please send me the Mudra loan documents checklist." },
    ],
    faq: mudraFaq,
  },
  "msme-loan": {
    title: `MSME Loan | ${site.companyName}`,
    description: "Bank and NBFC MSME loans from ₹50,000 to ₹5 crore with CGTMSE and working-capital pathways.",
    hero: {
      data: msmeLoanPage,
      images: { primary: photos.serviceLoan, secondary: photos.schemeGuarantee, circle: photos.schemeMudra, secondaryAlt: "MSME loan appraisal documents", circleAlt: "MSME founder reviewing credit options" },
      whatsappText: "Hi, I want to check eligibility for an MSME loan.",
    },
    unlock: { data: msmeLoanPage.unlock, image: { src: photos.serviceLoan, alt: "MSME loan financing support" } },
    sections: [
      { type: "services", data: msmeLoanPage.benefits, sectionId: "msme-loan-benefits" },
      { type: "categories", data: msmeLoanPage.eligibility, sectionId: "msme-loan-eligibility" },
      { type: "process", data: msmeLoanPage.process, sectionId: "msme-loan-process" },
      { type: "documents", data: msmeLoanPage.documents, sectionId: "msme-loan-documents", whatsappText: "Hi, please send me the MSME loan documents checklist." },
    ],
    faq: msmeLoanFaq,
  },
  standup: {
    title: `Stand-Up India | ${site.companyName}`,
    description: "Bank loans from ₹10 lakh to ₹1 crore for women entrepreneurs and SC/ST borrowers.",
    hero: {
      data: standupPage,
      images: { primary: photos.schemeStandup, secondary: photos.serviceLoan, circle: photos.schemePitch, secondaryAlt: "Stand-Up India business plan review", circleAlt: "Women entrepreneur loan application support" },
      whatsappText: "Hi, I want to check eligibility for Stand-Up India.",
    },
    unlock: { data: standupPage.unlock, image: { src: photos.schemeStandup, alt: "Stand-Up India loan facilitation" } },
    sections: [
      { type: "services", data: standupPage.benefits, sectionId: "standup-benefits" },
      { type: "categories", data: standupPage.eligibility, sectionId: "standup-eligibility" },
      { type: "process", data: standupPage.process, sectionId: "standup-process" },
      { type: "documents", data: standupPage.documents, sectionId: "standup-documents", whatsappText: "Hi, please send me the Stand-Up India documents checklist." },
    ],
    faq: standupFaq,
  },
  nbfc: {
    title: `NBFC Financing Solutions | ${site.companyName}`,
    description: "Faster NBFC business loans, working capital, LAP, machinery finance and invoice discounting with flexible eligibility.",
    hero: {
      data: nbfcPage,
      images: {
        primary: photos.aboutServiceNbf,
        secondary: photos.serviceLoan,
        circle: photos.schemeGuarantee,
        secondaryAlt: "NBFC loan documentation pack",
        circleAlt: "Founder reviewing NBFC financing options",
      },
      whatsappText: "Hi, I want to get NBFC loan options for my business.",
    },
    unlock: {
      data: nbfcPage.unlock,
      image: { src: photos.aboutServiceNbf, alt: "NBFC financing partner matching" },
    },
    sections: [
      { type: "categories", data: nbfcPage.categories, sectionId: "nbfc-products" },
      { type: "categories", data: nbfcPage.audience, sectionId: "nbfc-audience" },
      { type: "process", data: nbfcPage.process, sectionId: "nbfc-process" },
      { type: "services", data: nbfcPage.services, sectionId: "nbfc-why-choose" },
      { type: "services", data: nbfcPage.ecosystem, sectionId: "nbfc-ecosystem" },
    ],
    faq: nbfcFaq,
  },
  "business-loan-services": {
    title: `Business Loan Services | ${site.companyName}`,
    description: "Term loans, working capital, MSME priority lending and government scheme loans matched across banks and NBFCs.",
    hero: {
      data: loanPage,
      images: {
        primary: photos.aboutServiceLoans,
        secondary: photos.schemeMudra,
        circle: photos.schemeGuarantee,
        secondaryAlt: "Business loan product comparison",
        circleAlt: "Advisor preparing a lender-ready loan file",
      },
      whatsappText: "Hi, I want to start my business loan funding journey.",
    },
    unlock: {
      data: loanPage.unlock,
      image: { src: photos.aboutServiceLoans, alt: "Business loan advisory and lender matching" },
    },
    sections: [
      { type: "categories", data: loanPage.categories, sectionId: "loan-products" },
      { type: "services", data: loanPage.services, sectionId: "loan-why-choose" },
      { type: "process", data: loanPage.process, sectionId: "loan-process" },
      {
        type: "documents",
        data: loanPage.documents,
        sectionId: "loan-documents",
        whatsappText: "Hi, please send me the business loan documents checklist.",
      },
      { type: "categories", data: loanPage.schemes, sectionId: "loan-schemes" },
    ],
    faq: loanFaq,
  },
  "tax-exemption-certificate": {
    title: `Tax Exemption Certificate | ${site.companyName}`,
    description:
      "Section 80IAC tax exemption for DPIIT-recognised startups — up to 100% tax holiday for three consecutive years within the first decade.",
    hero: {
      data: taxExemptionCertificatePage,
      images: {
        primary: photos.aboutCertTax,
        secondary: photos.schemeTax,
        circle: photos.schemeStartup,
        secondaryAlt: "Startup tax compliance documentation",
        circleAlt: "Founders preparing Section 80IAC application",
      },
      whatsappText: "Hi, I want to check eligibility for a Tax Exemption Certificate under Section 80IAC.",
    },
    unlock: {
      data: taxExemptionCertificatePage.unlock,
      image: { src: photos.aboutCertTax, alt: "Tax Exemption Certificate under Section 80IAC" },
    },
    sections: [
      { type: "services", data: taxExemptionCertificatePage.benefits, sectionId: "tax-exemption-benefits" },
      { type: "categories", data: taxExemptionCertificatePage.eligibility, sectionId: "tax-exemption-eligibility" },
      { type: "process", data: taxExemptionCertificatePage.process, sectionId: "tax-exemption-process" },
      {
        type: "documents",
        data: taxExemptionCertificatePage.documents,
        sectionId: "tax-exemption-documents",
        whatsappText: "Hi, please send me the Tax Exemption Certificate documents checklist.",
      },
    ],
    faq: taxExemptionCertificateFaq,
  },
  "startup-india-eligibility": {
    title: `Startup India Scheme Eligibility | ${site.companyName}`,
    description:
      "2026 revised DPIIT Startup India eligibility — ₹200 Cr / ₹300 Cr turnover limits, Deep Tech age extension, and cooperative inclusion.",
    hero: {
      data: startupIndiaEligibilityPage,
      images: {
        primary: photos.schemeStartup,
        secondary: photos.schemeSeed,
        circle: photos.schemePitch,
        secondaryAlt: "Startup India recognition documentation",
        circleAlt: "Founders preparing DPIIT application",
      },
      whatsappText: "Hi, I want to check Startup India scheme eligibility under the 2026 revised criteria.",
    },
    unlock: {
      data: startupIndiaEligibilityPage.unlock,
      image: { src: photos.schemeStartup, alt: "Startup India DPIIT recognition eligibility" },
    },
    sections: [
      { type: "services", data: startupIndiaEligibilityPage.benefits, sectionId: "startup-eligibility-benefits" },
      { type: "categories", data: startupIndiaEligibilityPage.eligibility, sectionId: "startup-eligibility-criteria" },
      { type: "process", data: startupIndiaEligibilityPage.process, sectionId: "startup-eligibility-process" },
      {
        type: "documents",
        data: startupIndiaEligibilityPage.documents,
        sectionId: "startup-eligibility-documents",
        whatsappText: "Hi, please send me the DPIIT recognition documents checklist.",
      },
    ],
    faq: startupIndiaEligibilityFaq,
  },
  "act-grant": {
    title: `ACT Grants | ${site.companyName}`,
    description: "ACT Grants — grant support of about ₹5L–₹50L for qualifying innovators and startups.",
    hero: {
      data: actGrantPage,
      images: { primary: photos.schemeSeed, secondary: photos.schemeStartup, circle: photos.schemePitch, secondaryAlt: "ACT Grants application support", circleAlt: "Founders preparing a ACT Grants proposal" },
      whatsappText: "Hi, I want to check eligibility for ACT Grants.",
    },
    unlock: { data: actGrantPage.unlock, image: { src: photos.schemeSeed, alt: "ACT Grants grant support" } },
    sections: [
      { type: "services", data: actGrantPage.benefits, sectionId: "actGrant-benefits" },
      { type: "categories", data: actGrantPage.eligibility, sectionId: "actGrant-eligibility" },
      { type: "process", data: actGrantPage.process, sectionId: "actGrant-process" },
      { type: "documents", data: actGrantPage.documents, sectionId: "actGrant-documents", whatsappText: "Hi, please send me the ACT Grants documents checklist." },
    ],
    faq: actGrantFaq,
  },
  "mahila-empowerment": {
    title: `Mahila Empowerment Scheme | ${site.companyName}`,
    description: "Mahila Empowerment Scheme — grant support of about Up to ₹15L for qualifying innovators and startups.",
    hero: {
      data: mahilaEmpowermentPage,
      images: { primary: photos.schemeStartup, secondary: photos.schemePitch, circle: photos.schemeVc, secondaryAlt: "Mahila Empowerment Scheme application support", circleAlt: "Founders preparing a Mahila Empowerment Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for Mahila Empowerment Scheme.",
    },
    unlock: { data: mahilaEmpowermentPage.unlock, image: { src: photos.schemeStartup, alt: "Mahila Empowerment Scheme grant support" } },
    sections: [
      { type: "services", data: mahilaEmpowermentPage.benefits, sectionId: "mahilaEmpowerment-benefits" },
      { type: "categories", data: mahilaEmpowermentPage.eligibility, sectionId: "mahilaEmpowerment-eligibility" },
      { type: "process", data: mahilaEmpowermentPage.process, sectionId: "mahilaEmpowerment-process" },
      { type: "documents", data: mahilaEmpowermentPage.documents, sectionId: "mahilaEmpowerment-documents", whatsappText: "Hi, please send me the Mahila Empowerment Scheme documents checklist." },
    ],
    faq: mahilaEmpowermentFaq,
  },
  "spark-grant": {
    title: `Spark Grant | ${site.companyName}`,
    description: "Spark Grant — grant support of about Up to ₹88L for qualifying innovators and startups.",
    hero: {
      data: sparkGrantPage,
      images: { primary: photos.schemePitch, secondary: photos.schemeVc, circle: photos.schemeLab, secondaryAlt: "Spark Grant application support", circleAlt: "Founders preparing a Spark Grant proposal" },
      whatsappText: "Hi, I want to check eligibility for Spark Grant.",
    },
    unlock: { data: sparkGrantPage.unlock, image: { src: photos.schemePitch, alt: "Spark Grant grant support" } },
    sections: [
      { type: "services", data: sparkGrantPage.benefits, sectionId: "sparkGrant-benefits" },
      { type: "categories", data: sparkGrantPage.eligibility, sectionId: "sparkGrant-eligibility" },
      { type: "process", data: sparkGrantPage.process, sectionId: "sparkGrant-process" },
      { type: "documents", data: sparkGrantPage.documents, sectionId: "sparkGrant-documents", whatsappText: "Hi, please send me the Spark Grant documents checklist." },
    ],
    faq: sparkGrantFaq,
  },
  "tide-2": {
    title: `TIDE 2.0 Scheme | ${site.companyName}`,
    description: "TIDE 2.0 Scheme — grant support of about Up to ₹7L for qualifying innovators and startups.",
    hero: {
      data: tide2Page,
      images: { primary: photos.schemeVc, secondary: photos.schemeLab, circle: photos.schemeTech, secondaryAlt: "TIDE 2.0 Scheme application support", circleAlt: "Founders preparing a TIDE 2.0 Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for TIDE 2.0 Scheme.",
    },
    unlock: { data: tide2Page.unlock, image: { src: photos.schemeVc, alt: "TIDE 2.0 Scheme grant support" } },
    sections: [
      { type: "services", data: tide2Page.benefits, sectionId: "tide2-benefits" },
      { type: "categories", data: tide2Page.eligibility, sectionId: "tide2-eligibility" },
      { type: "process", data: tide2Page.process, sectionId: "tide2-process" },
      { type: "documents", data: tide2Page.documents, sectionId: "tide2-documents", whatsappText: "Hi, please send me the TIDE 2.0 Scheme documents checklist." },
    ],
    faq: tide2Faq,
  },
  "rkvy-raftaar": {
    title: `RKVY RAFTAAR | ${site.companyName}`,
    description: "RKVY RAFTAAR — grant support of about Up to ₹25L for qualifying innovators and startups.",
    hero: {
      data: rkvyRaftaarPage,
      images: { primary: photos.schemeLab, secondary: photos.schemeTech, circle: photos.schemeAgri, secondaryAlt: "RKVY RAFTAAR application support", circleAlt: "Founders preparing a RKVY RAFTAAR proposal" },
      whatsappText: "Hi, I want to check eligibility for RKVY RAFTAAR.",
    },
    unlock: { data: rkvyRaftaarPage.unlock, image: { src: photos.schemeLab, alt: "RKVY RAFTAAR grant support" } },
    sections: [
      { type: "services", data: rkvyRaftaarPage.benefits, sectionId: "rkvyRaftaar-benefits" },
      { type: "categories", data: rkvyRaftaarPage.eligibility, sectionId: "rkvyRaftaar-eligibility" },
      { type: "process", data: rkvyRaftaarPage.process, sectionId: "rkvyRaftaar-process" },
      { type: "documents", data: rkvyRaftaarPage.documents, sectionId: "rkvyRaftaar-documents", whatsappText: "Hi, please send me the RKVY RAFTAAR documents checklist." },
    ],
    faq: rkvyRaftaarFaq,
  },
  "nidhi-prayas": {
    title: `NIDHI PRAYAS Grant | ${site.companyName}`,
    description: "NIDHI PRAYAS Grant — grant support of about Up to ₹10L for qualifying innovators and startups.",
    hero: {
      data: nidhiPrayasPage,
      images: { primary: photos.schemeTech, secondary: photos.schemeAgri, circle: photos.aboutServiceGrants, secondaryAlt: "NIDHI PRAYAS Grant application support", circleAlt: "Founders preparing a NIDHI PRAYAS Grant proposal" },
      whatsappText: "Hi, I want to check eligibility for NIDHI PRAYAS Grant.",
    },
    unlock: { data: nidhiPrayasPage.unlock, image: { src: photos.schemeTech, alt: "NIDHI PRAYAS Grant grant support" } },
    sections: [
      { type: "services", data: nidhiPrayasPage.benefits, sectionId: "nidhiPrayas-benefits" },
      { type: "categories", data: nidhiPrayasPage.eligibility, sectionId: "nidhiPrayas-eligibility" },
      { type: "process", data: nidhiPrayasPage.process, sectionId: "nidhiPrayas-process" },
      { type: "documents", data: nidhiPrayasPage.documents, sectionId: "nidhiPrayas-documents", whatsappText: "Hi, please send me the NIDHI PRAYAS Grant documents checklist." },
    ],
    faq: nidhiPrayasFaq,
  },
  "meity-genesis-eir": {
    title: `MeitY GENESIS EIR | ${site.companyName}`,
    description: "MeitY GENESIS EIR — grant support of about Up to ₹10L for qualifying innovators and startups.",
    hero: {
      data: meityGenesisEirPage,
      images: { primary: photos.schemeAgri, secondary: photos.aboutServiceGrants, circle: photos.schemeGuarantee, secondaryAlt: "MeitY GENESIS EIR application support", circleAlt: "Founders preparing a MeitY GENESIS EIR proposal" },
      whatsappText: "Hi, I want to check eligibility for MeitY GENESIS EIR.",
    },
    unlock: { data: meityGenesisEirPage.unlock, image: { src: photos.schemeAgri, alt: "MeitY GENESIS EIR grant support" } },
    sections: [
      { type: "services", data: meityGenesisEirPage.benefits, sectionId: "meityGenesisEir-benefits" },
      { type: "categories", data: meityGenesisEirPage.eligibility, sectionId: "meityGenesisEir-eligibility" },
      { type: "process", data: meityGenesisEirPage.process, sectionId: "meityGenesisEir-process" },
      { type: "documents", data: meityGenesisEirPage.documents, sectionId: "meityGenesisEir-documents", whatsappText: "Hi, please send me the MeitY GENESIS EIR documents checklist." },
    ],
    faq: meityGenesisEirFaq,
  },
  "agri-business-grants": {
    title: `Agri Business Grants | ${site.companyName}`,
    description: "Agri Business Grants — grant support of about Up to ₹40L for qualifying innovators and startups.",
    hero: {
      data: agriBusinessGrantsPage,
      images: { primary: photos.aboutServiceGrants, secondary: photos.schemeGuarantee, circle: photos.schemeSeed, secondaryAlt: "Agri Business Grants application support", circleAlt: "Founders preparing a Agri Business Grants proposal" },
      whatsappText: "Hi, I want to check eligibility for Agri Business Grants.",
    },
    unlock: { data: agriBusinessGrantsPage.unlock, image: { src: photos.aboutServiceGrants, alt: "Agri Business Grants grant support" } },
    sections: [
      { type: "services", data: agriBusinessGrantsPage.benefits, sectionId: "agriBusinessGrants-benefits" },
      { type: "categories", data: agriBusinessGrantsPage.eligibility, sectionId: "agriBusinessGrants-eligibility" },
      { type: "process", data: agriBusinessGrantsPage.process, sectionId: "agriBusinessGrants-process" },
      { type: "documents", data: agriBusinessGrantsPage.documents, sectionId: "agriBusinessGrants-documents", whatsappText: "Hi, please send me the Agri Business Grants documents checklist." },
    ],
    faq: agriBusinessGrantsFaq,
  },
  "social-impact": {
    title: `Social Impact Innovation Scheme | ${site.companyName}`,
    description: "Social Impact Innovation Scheme — grant support of about Up to ₹5L for qualifying innovators and startups.",
    hero: {
      data: socialImpactPage,
      images: { primary: photos.schemeGuarantee, secondary: photos.schemeSeed, circle: photos.schemeStartup, secondaryAlt: "Social Impact Innovation Scheme application support", circleAlt: "Founders preparing a Social Impact Innovation Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for Social Impact Innovation Scheme.",
    },
    unlock: { data: socialImpactPage.unlock, image: { src: photos.schemeGuarantee, alt: "Social Impact Innovation Scheme grant support" } },
    sections: [
      { type: "services", data: socialImpactPage.benefits, sectionId: "socialImpact-benefits" },
      { type: "categories", data: socialImpactPage.eligibility, sectionId: "socialImpact-eligibility" },
      { type: "process", data: socialImpactPage.process, sectionId: "socialImpact-process" },
      { type: "documents", data: socialImpactPage.documents, sectionId: "socialImpact-documents", whatsappText: "Hi, please send me the Social Impact Innovation Scheme documents checklist." },
    ],
    faq: socialImpactFaq,
  },
  "mobility-innovation": {
    title: `Mobility Innovation Program | ${site.companyName}`,
    description: "Mobility Innovation Program — grant support of about Up to ₹10L for qualifying innovators and startups.",
    hero: {
      data: mobilityInnovationPage,
      images: { primary: photos.schemeSeed, secondary: photos.schemeStartup, circle: photos.schemePitch, secondaryAlt: "Mobility Innovation Program application support", circleAlt: "Founders preparing a Mobility Innovation Program proposal" },
      whatsappText: "Hi, I want to check eligibility for Mobility Innovation Program.",
    },
    unlock: { data: mobilityInnovationPage.unlock, image: { src: photos.schemeSeed, alt: "Mobility Innovation Program grant support" } },
    sections: [
      { type: "services", data: mobilityInnovationPage.benefits, sectionId: "mobilityInnovation-benefits" },
      { type: "categories", data: mobilityInnovationPage.eligibility, sectionId: "mobilityInnovation-eligibility" },
      { type: "process", data: mobilityInnovationPage.process, sectionId: "mobilityInnovation-process" },
      { type: "documents", data: mobilityInnovationPage.documents, sectionId: "mobilityInnovation-documents", whatsappText: "Hi, please send me the Mobility Innovation Program documents checklist." },
    ],
    faq: mobilityInnovationFaq,
  },
  "great-scheme": {
    title: `GREAT Scheme | ${site.companyName}`,
    description: "GREAT Scheme — grant support of about Up to ₹50L for qualifying innovators and startups.",
    hero: {
      data: greatSchemePage,
      images: { primary: photos.schemeStartup, secondary: photos.schemePitch, circle: photos.schemeVc, secondaryAlt: "GREAT Scheme application support", circleAlt: "Founders preparing a GREAT Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for GREAT Scheme.",
    },
    unlock: { data: greatSchemePage.unlock, image: { src: photos.schemeStartup, alt: "GREAT Scheme grant support" } },
    sections: [
      { type: "services", data: greatSchemePage.benefits, sectionId: "greatScheme-benefits" },
      { type: "categories", data: greatSchemePage.eligibility, sectionId: "greatScheme-eligibility" },
      { type: "process", data: greatSchemePage.process, sectionId: "greatScheme-process" },
      { type: "documents", data: greatSchemePage.documents, sectionId: "greatScheme-documents", whatsappText: "Hi, please send me the GREAT Scheme documents checklist." },
    ],
    faq: greatSchemeFaq,
  },
  "uyegp": {
    title: `UYEGP Scheme | ${site.companyName}`,
    description: "UYEGP Scheme — grant support of about Up to ₹15L for qualifying innovators and startups.",
    hero: {
      data: uyegpPage,
      images: { primary: photos.schemePitch, secondary: photos.schemeVc, circle: photos.schemeLab, secondaryAlt: "UYEGP Scheme application support", circleAlt: "Founders preparing a UYEGP Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for UYEGP Scheme.",
    },
    unlock: { data: uyegpPage.unlock, image: { src: photos.schemePitch, alt: "UYEGP Scheme grant support" } },
    sections: [
      { type: "services", data: uyegpPage.benefits, sectionId: "uyegp-benefits" },
      { type: "categories", data: uyegpPage.eligibility, sectionId: "uyegp-eligibility" },
      { type: "process", data: uyegpPage.process, sectionId: "uyegp-process" },
      { type: "documents", data: uyegpPage.documents, sectionId: "uyegp-documents", whatsappText: "Hi, please send me the UYEGP Scheme documents checklist." },
    ],
    faq: uyegpFaq,
  },
  "cybersecurity-fund": {
    title: `Cybersecurity Fund 2.0 | ${site.companyName}`,
    description: "Cybersecurity Fund 2.0 — grant support of about Up to ₹30L for qualifying innovators and startups.",
    hero: {
      data: cybersecurityFundPage,
      images: { primary: photos.schemeVc, secondary: photos.schemeLab, circle: photos.schemeTech, secondaryAlt: "Cybersecurity Fund 2.0 application support", circleAlt: "Founders preparing a Cybersecurity Fund 2.0 proposal" },
      whatsappText: "Hi, I want to check eligibility for Cybersecurity Fund 2.0.",
    },
    unlock: { data: cybersecurityFundPage.unlock, image: { src: photos.schemeVc, alt: "Cybersecurity Fund 2.0 grant support" } },
    sections: [
      { type: "services", data: cybersecurityFundPage.benefits, sectionId: "cybersecurityFund-benefits" },
      { type: "categories", data: cybersecurityFundPage.eligibility, sectionId: "cybersecurityFund-eligibility" },
      { type: "process", data: cybersecurityFundPage.process, sectionId: "cybersecurityFund-process" },
      { type: "documents", data: cybersecurityFundPage.documents, sectionId: "cybersecurityFund-documents", whatsappText: "Hi, please send me the Cybersecurity Fund 2.0 documents checklist." },
    ],
    faq: cybersecurityFundFaq,
  },
  "art-program": {
    title: `ART Program | ${site.companyName}`,
    description: "ART Program — grant support of about Up to ₹30L for qualifying innovators and startups.",
    hero: {
      data: artProgramPage,
      images: { primary: photos.schemeLab, secondary: photos.schemeTech, circle: photos.schemeAgri, secondaryAlt: "ART Program application support", circleAlt: "Founders preparing a ART Program proposal" },
      whatsappText: "Hi, I want to check eligibility for ART Program.",
    },
    unlock: { data: artProgramPage.unlock, image: { src: photos.schemeLab, alt: "ART Program grant support" } },
    sections: [
      { type: "services", data: artProgramPage.benefits, sectionId: "artProgram-benefits" },
      { type: "categories", data: artProgramPage.eligibility, sectionId: "artProgram-eligibility" },
      { type: "process", data: artProgramPage.process, sectionId: "artProgram-process" },
      { type: "documents", data: artProgramPage.documents, sectionId: "artProgram-documents", whatsappText: "Hi, please send me the ART Program documents checklist." },
    ],
    faq: artProgramFaq,
  },
  "agri-sure-fund": {
    title: `Agri-Sure Fund | ${site.companyName}`,
    description: "Agri-Sure Fund — grant support of about Up to ₹25L for qualifying innovators and startups.",
    hero: {
      data: agriSureFundPage,
      images: { primary: photos.schemeTech, secondary: photos.schemeAgri, circle: photos.aboutServiceGrants, secondaryAlt: "Agri-Sure Fund application support", circleAlt: "Founders preparing a Agri-Sure Fund proposal" },
      whatsappText: "Hi, I want to check eligibility for Agri-Sure Fund.",
    },
    unlock: { data: agriSureFundPage.unlock, image: { src: photos.schemeTech, alt: "Agri-Sure Fund grant support" } },
    sections: [
      { type: "services", data: agriSureFundPage.benefits, sectionId: "agriSureFund-benefits" },
      { type: "categories", data: agriSureFundPage.eligibility, sectionId: "agriSureFund-eligibility" },
      { type: "process", data: agriSureFundPage.process, sectionId: "agriSureFund-process" },
      { type: "documents", data: agriSureFundPage.documents, sectionId: "agriSureFund-documents", whatsappText: "Hi, please send me the Agri-Sure Fund documents checklist." },
    ],
    faq: agriSureFundFaq,
  },
  "grant-for-ventures": {
    title: `Grant for Ventures | ${site.companyName}`,
    description: "Grant for Ventures — grant support of about Up to ₹30L for qualifying innovators and startups.",
    hero: {
      data: grantForVenturesPage,
      images: { primary: photos.schemeAgri, secondary: photos.aboutServiceGrants, circle: photos.schemeGuarantee, secondaryAlt: "Grant for Ventures application support", circleAlt: "Founders preparing a Grant for Ventures proposal" },
      whatsappText: "Hi, I want to check eligibility for Grant for Ventures.",
    },
    unlock: { data: grantForVenturesPage.unlock, image: { src: photos.schemeAgri, alt: "Grant for Ventures grant support" } },
    sections: [
      { type: "services", data: grantForVenturesPage.benefits, sectionId: "grantForVentures-benefits" },
      { type: "categories", data: grantForVenturesPage.eligibility, sectionId: "grantForVentures-eligibility" },
      { type: "process", data: grantForVenturesPage.process, sectionId: "grantForVentures-process" },
      { type: "documents", data: grantForVenturesPage.documents, sectionId: "grantForVentures-documents", whatsappText: "Hi, please send me the Grant for Ventures documents checklist." },
    ],
    faq: grantForVenturesFaq,
  },
  "growth-grant": {
    title: `Growth Grant | ${site.companyName}`,
    description: "Growth Grant — grant support of about Up to ₹1.7Cr for qualifying innovators and startups.",
    hero: {
      data: growthGrantPage,
      images: { primary: photos.aboutServiceGrants, secondary: photos.schemeGuarantee, circle: photos.schemeSeed, secondaryAlt: "Growth Grant application support", circleAlt: "Founders preparing a Growth Grant proposal" },
      whatsappText: "Hi, I want to check eligibility for Growth Grant.",
    },
    unlock: { data: growthGrantPage.unlock, image: { src: photos.aboutServiceGrants, alt: "Growth Grant grant support" } },
    sections: [
      { type: "services", data: growthGrantPage.benefits, sectionId: "growthGrant-benefits" },
      { type: "categories", data: growthGrantPage.eligibility, sectionId: "growthGrant-eligibility" },
      { type: "process", data: growthGrantPage.process, sectionId: "growthGrant-process" },
      { type: "documents", data: growthGrantPage.documents, sectionId: "growthGrant-documents", whatsappText: "Hi, please send me the Growth Grant documents checklist." },
    ],
    faq: growthGrantFaq,
  },
  "brightpath-ventures": {
    title: `BrightPath Ventures | ${site.companyName}`,
    description: "BrightPath Ventures — grant support of about Up to ₹18Cr for qualifying innovators and startups.",
    hero: {
      data: brightpathVenturesPage,
      images: { primary: photos.schemeGuarantee, secondary: photos.schemeSeed, circle: photos.schemeStartup, secondaryAlt: "BrightPath Ventures application support", circleAlt: "Founders preparing a BrightPath Ventures proposal" },
      whatsappText: "Hi, I want to check eligibility for BrightPath Ventures.",
    },
    unlock: { data: brightpathVenturesPage.unlock, image: { src: photos.schemeGuarantee, alt: "BrightPath Ventures grant support" } },
    sections: [
      { type: "services", data: brightpathVenturesPage.benefits, sectionId: "brightpathVentures-benefits" },
      { type: "categories", data: brightpathVenturesPage.eligibility, sectionId: "brightpathVentures-eligibility" },
      { type: "process", data: brightpathVenturesPage.process, sectionId: "brightpathVentures-process" },
      { type: "documents", data: brightpathVenturesPage.documents, sectionId: "brightpathVentures-documents", whatsappText: "Hi, please send me the BrightPath Ventures documents checklist." },
    ],
    faq: brightpathVenturesFaq,
  },
  "health-accelerator": {
    title: `Health Accelerator | ${site.companyName}`,
    description: "Health Accelerator — grant support of about Up to ₹10L for qualifying innovators and startups.",
    hero: {
      data: healthAcceleratorPage,
      images: { primary: photos.schemeSeed, secondary: photos.schemeStartup, circle: photos.schemePitch, secondaryAlt: "Health Accelerator application support", circleAlt: "Founders preparing a Health Accelerator proposal" },
      whatsappText: "Hi, I want to check eligibility for Health Accelerator.",
    },
    unlock: { data: healthAcceleratorPage.unlock, image: { src: photos.schemeSeed, alt: "Health Accelerator grant support" } },
    sections: [
      { type: "services", data: healthAcceleratorPage.benefits, sectionId: "healthAccelerator-benefits" },
      { type: "categories", data: healthAcceleratorPage.eligibility, sectionId: "healthAccelerator-eligibility" },
      { type: "process", data: healthAcceleratorPage.process, sectionId: "healthAccelerator-process" },
      { type: "documents", data: healthAcceleratorPage.documents, sectionId: "healthAccelerator-documents", whatsappText: "Hi, please send me the Health Accelerator documents checklist." },
    ],
    faq: healthAcceleratorFaq,
  },
  "startup-accelerator": {
    title: `Startup Accelerator Scheme | ${site.companyName}`,
    description: "Startup Accelerator Scheme — grant support of about Up to ₹25L for qualifying innovators and startups.",
    hero: {
      data: startupAcceleratorPage,
      images: { primary: photos.schemeStartup, secondary: photos.schemePitch, circle: photos.schemeVc, secondaryAlt: "Startup Accelerator Scheme application support", circleAlt: "Founders preparing a Startup Accelerator Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for Startup Accelerator Scheme.",
    },
    unlock: { data: startupAcceleratorPage.unlock, image: { src: photos.schemeStartup, alt: "Startup Accelerator Scheme grant support" } },
    sections: [
      { type: "services", data: startupAcceleratorPage.benefits, sectionId: "startupAccelerator-benefits" },
      { type: "categories", data: startupAcceleratorPage.eligibility, sectionId: "startupAccelerator-eligibility" },
      { type: "process", data: startupAcceleratorPage.process, sectionId: "startupAccelerator-process" },
      { type: "documents", data: startupAcceleratorPage.documents, sectionId: "startupAccelerator-documents", whatsappText: "Hi, please send me the Startup Accelerator Scheme documents checklist." },
    ],
    faq: startupAcceleratorFaq,
  },
  "startup-spark": {
    title: `Startup Spark Scheme | ${site.companyName}`,
    description: "Startup Spark Scheme — grant support of about Up to ₹50L for qualifying innovators and startups.",
    hero: {
      data: startupSparkPage,
      images: { primary: photos.schemePitch, secondary: photos.schemeVc, circle: photos.schemeLab, secondaryAlt: "Startup Spark Scheme application support", circleAlt: "Founders preparing a Startup Spark Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for Startup Spark Scheme.",
    },
    unlock: { data: startupSparkPage.unlock, image: { src: photos.schemePitch, alt: "Startup Spark Scheme grant support" } },
    sections: [
      { type: "services", data: startupSparkPage.benefits, sectionId: "startupSpark-benefits" },
      { type: "categories", data: startupSparkPage.eligibility, sectionId: "startupSpark-eligibility" },
      { type: "process", data: startupSparkPage.process, sectionId: "startupSpark-process" },
      { type: "documents", data: startupSparkPage.documents, sectionId: "startupSpark-documents", whatsappText: "Hi, please send me the Startup Spark Scheme documents checklist." },
    ],
    faq: startupSparkFaq,
  },
  "leap-fund-scheme": {
    title: `Leap Fund Scheme | ${site.companyName}`,
    description: "Leap Fund Scheme — grant support of about Up to ₹1Cr for qualifying innovators and startups.",
    hero: {
      data: leapFundSchemePage,
      images: { primary: photos.schemeVc, secondary: photos.schemeLab, circle: photos.schemeTech, secondaryAlt: "Leap Fund Scheme application support", circleAlt: "Founders preparing a Leap Fund Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for Leap Fund Scheme.",
    },
    unlock: { data: leapFundSchemePage.unlock, image: { src: photos.schemeVc, alt: "Leap Fund Scheme grant support" } },
    sections: [
      { type: "services", data: leapFundSchemePage.benefits, sectionId: "leapFundScheme-benefits" },
      { type: "categories", data: leapFundSchemePage.eligibility, sectionId: "leapFundScheme-eligibility" },
      { type: "process", data: leapFundSchemePage.process, sectionId: "leapFundScheme-process" },
      { type: "documents", data: leapFundSchemePage.documents, sectionId: "leapFundScheme-documents", whatsappText: "Hi, please send me the Leap Fund Scheme documents checklist." },
    ],
    faq: leapFundSchemeFaq,
  },
  "hp-udgam": {
    title: `HP Udgam Scheme | ${site.companyName}`,
    description: "HP Udgam Scheme — grant support of about Up to ₹2.5Cr for qualifying innovators and startups.",
    hero: {
      data: hpUdgamPage,
      images: { primary: photos.schemeLab, secondary: photos.schemeTech, circle: photos.schemeAgri, secondaryAlt: "HP Udgam Scheme application support", circleAlt: "Founders preparing a HP Udgam Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for HP Udgam Scheme.",
    },
    unlock: { data: hpUdgamPage.unlock, image: { src: photos.schemeLab, alt: "HP Udgam Scheme grant support" } },
    sections: [
      { type: "services", data: hpUdgamPage.benefits, sectionId: "hpUdgam-benefits" },
      { type: "categories", data: hpUdgamPage.eligibility, sectionId: "hpUdgam-eligibility" },
      { type: "process", data: hpUdgamPage.process, sectionId: "hpUdgam-process" },
      { type: "documents", data: hpUdgamPage.documents, sectionId: "hpUdgam-documents", whatsappText: "Hi, please send me the HP Udgam Scheme documents checklist." },
    ],
    faq: hpUdgamFaq,
  },
  "defence-scheme": {
    title: `iDEX Defence Innovation Scheme | ${site.companyName}`,
    description: "iDEX Defence Innovation Scheme — grant support of about Up to ₹1.5Cr for qualifying innovators and startups.",
    hero: {
      data: defenceSchemePage,
      images: { primary: photos.schemeTech, secondary: photos.schemeAgri, circle: photos.aboutServiceGrants, secondaryAlt: "iDEX Defence Innovation Scheme application support", circleAlt: "Founders preparing a iDEX Defence Innovation Scheme proposal" },
      whatsappText: "Hi, I want to check eligibility for iDEX Defence Innovation Scheme.",
    },
    unlock: { data: defenceSchemePage.unlock, image: { src: photos.schemeTech, alt: "iDEX Defence Innovation Scheme grant support" } },
    sections: [
      { type: "services", data: defenceSchemePage.benefits, sectionId: "defenceScheme-benefits" },
      { type: "categories", data: defenceSchemePage.eligibility, sectionId: "defenceScheme-eligibility" },
      { type: "process", data: defenceSchemePage.process, sectionId: "defenceScheme-process" },
      { type: "documents", data: defenceSchemePage.documents, sectionId: "defenceScheme-documents", whatsappText: "Hi, please send me the iDEX Defence Innovation Scheme documents checklist." },
    ],
    faq: defenceSchemeFaq,
  },
  "aditi-defence": {
    title: `Aditi Defence 4.0 Challenge | ${site.companyName}`,
    description: "Aditi Defence 4.0 Challenge — grant support of about Up to ₹25Cr for qualifying innovators and startups.",
    hero: {
      data: aditiDefencePage,
      images: { primary: photos.schemeAgri, secondary: photos.aboutServiceGrants, circle: photos.schemeGuarantee, secondaryAlt: "Aditi Defence 4.0 Challenge application support", circleAlt: "Founders preparing a Aditi Defence 4.0 Challenge proposal" },
      whatsappText: "Hi, I want to check eligibility for Aditi Defence 4.0 Challenge.",
    },
    unlock: { data: aditiDefencePage.unlock, image: { src: photos.schemeAgri, alt: "Aditi Defence 4.0 Challenge grant support" } },
    sections: [
      { type: "services", data: aditiDefencePage.benefits, sectionId: "aditiDefence-benefits" },
      { type: "categories", data: aditiDefencePage.eligibility, sectionId: "aditiDefence-eligibility" },
      { type: "process", data: aditiDefencePage.process, sectionId: "aditiDefence-process" },
      { type: "documents", data: aditiDefencePage.documents, sectionId: "aditiDefence-documents", whatsappText: "Hi, please send me the Aditi Defence 4.0 Challenge documents checklist." },
    ],
    faq: aditiDefenceFaq,
  },
  "aerospace-defence": {
    title: `Aerospace Defence Fund | ${site.companyName}`,
    description: "Aerospace Defence Fund — grant support of about Up to ₹25Cr for qualifying innovators and startups.",
    hero: {
      data: aerospaceDefencePage,
      images: { primary: photos.aboutServiceGrants, secondary: photos.schemeGuarantee, circle: photos.schemeSeed, secondaryAlt: "Aerospace Defence Fund application support", circleAlt: "Founders preparing a Aerospace Defence Fund proposal" },
      whatsappText: "Hi, I want to check eligibility for Aerospace Defence Fund.",
    },
    unlock: { data: aerospaceDefencePage.unlock, image: { src: photos.aboutServiceGrants, alt: "Aerospace Defence Fund grant support" } },
    sections: [
      { type: "services", data: aerospaceDefencePage.benefits, sectionId: "aerospaceDefence-benefits" },
      { type: "categories", data: aerospaceDefencePage.eligibility, sectionId: "aerospaceDefence-eligibility" },
      { type: "process", data: aerospaceDefencePage.process, sectionId: "aerospaceDefence-process" },
      { type: "documents", data: aerospaceDefencePage.documents, sectionId: "aerospaceDefence-documents", whatsappText: "Hi, please send me the Aerospace Defence Fund documents checklist." },
    ],
    faq: aerospaceDefenceFaq,
  },
  "agri-startup-shitij": {
    title: `Agri Startup Fund (SHITIJ 2.0) | ${site.companyName}`,
    description: "Agri Startup Fund (SHITIJ 2.0) — grant support of about Incubation for qualifying innovators and startups.",
    hero: {
      data: agriStartupShitijPage,
      images: { primary: photos.schemeGuarantee, secondary: photos.schemeSeed, circle: photos.schemeStartup, secondaryAlt: "Agri Startup Fund (SHITIJ 2.0) application support", circleAlt: "Founders preparing a Agri Startup Fund (SHITIJ 2.0) proposal" },
      whatsappText: "Hi, I want to check eligibility for Agri Startup Fund (SHITIJ 2.0).",
    },
    unlock: { data: agriStartupShitijPage.unlock, image: { src: photos.schemeGuarantee, alt: "Agri Startup Fund (SHITIJ 2.0) grant support" } },
    sections: [
      { type: "services", data: agriStartupShitijPage.benefits, sectionId: "agriStartupShitij-benefits" },
      { type: "categories", data: agriStartupShitijPage.eligibility, sectionId: "agriStartupShitij-eligibility" },
      { type: "process", data: agriStartupShitijPage.process, sectionId: "agriStartupShitij-process" },
      { type: "documents", data: agriStartupShitijPage.documents, sectionId: "agriStartupShitij-documents", whatsappText: "Hi, please send me the Agri Startup Fund (SHITIJ 2.0) documents checklist." },
    ],
    faq: agriStartupShitijFaq,
  },
  "agri-tech-fund": {
    title: `Agri-Tech Fund Assistance | ${site.companyName}`,
    description: "Agri-Tech Fund Assistance — grant support of about Up to ₹35L for qualifying innovators and startups.",
    hero: {
      data: agriTechFundPage,
      images: { primary: photos.schemeSeed, secondary: photos.schemeStartup, circle: photos.schemePitch, secondaryAlt: "Agri-Tech Fund Assistance application support", circleAlt: "Founders preparing a Agri-Tech Fund Assistance proposal" },
      whatsappText: "Hi, I want to check eligibility for Agri-Tech Fund Assistance.",
    },
    unlock: { data: agriTechFundPage.unlock, image: { src: photos.schemeSeed, alt: "Agri-Tech Fund Assistance grant support" } },
    sections: [
      { type: "services", data: agriTechFundPage.benefits, sectionId: "agriTechFund-benefits" },
      { type: "categories", data: agriTechFundPage.eligibility, sectionId: "agriTechFund-eligibility" },
      { type: "process", data: agriTechFundPage.process, sectionId: "agriTechFund-process" },
      { type: "documents", data: agriTechFundPage.documents, sectionId: "agriTechFund-documents", whatsappText: "Hi, please send me the Agri-Tech Fund Assistance documents checklist." },
    ],
    faq: agriTechFundFaq,
  },
  "agrinext": {
    title: `AgriNext | ${site.companyName}`,
    description: "AgriNext — grant support of about Up to ₹25L for qualifying innovators and startups.",
    hero: {
      data: agrinextPage,
      images: { primary: photos.schemeStartup, secondary: photos.schemePitch, circle: photos.schemeVc, secondaryAlt: "AgriNext application support", circleAlt: "Founders preparing a AgriNext proposal" },
      whatsappText: "Hi, I want to check eligibility for AgriNext.",
    },
    unlock: { data: agrinextPage.unlock, image: { src: photos.schemeStartup, alt: "AgriNext grant support" } },
    sections: [
      { type: "services", data: agrinextPage.benefits, sectionId: "agrinext-benefits" },
      { type: "categories", data: agrinextPage.eligibility, sectionId: "agrinext-eligibility" },
      { type: "process", data: agrinextPage.process, sectionId: "agrinext-process" },
      { type: "documents", data: agrinextPage.documents, sectionId: "agrinext-documents", whatsappText: "Hi, please send me the AgriNext documents checklist." },
    ],
    faq: agrinextFaq,
  },
  "loreal-green": {
    title: `L'Oréal Green Sciences Incubator | ${site.companyName}`,
    description: "L'Oréal Green Sciences Incubator — grant support of about Up to €100K for qualifying innovators and startups.",
    hero: {
      data: lorealGreenPage,
      images: { primary: photos.schemePitch, secondary: photos.schemeVc, circle: photos.schemeLab, secondaryAlt: "L'Oréal Green Sciences Incubator application support", circleAlt: "Founders preparing a L'Oréal Green Sciences Incubator proposal" },
      whatsappText: "Hi, I want to check eligibility for L'Oréal Green Sciences Incubator.",
    },
    unlock: { data: lorealGreenPage.unlock, image: { src: photos.schemePitch, alt: "L'Oréal Green Sciences Incubator grant support" } },
    sections: [
      { type: "services", data: lorealGreenPage.benefits, sectionId: "lorealGreen-benefits" },
      { type: "categories", data: lorealGreenPage.eligibility, sectionId: "lorealGreen-eligibility" },
      { type: "process", data: lorealGreenPage.process, sectionId: "lorealGreen-process" },
      { type: "documents", data: lorealGreenPage.documents, sectionId: "lorealGreen-documents", whatsappText: "Hi, please send me the L'Oréal Green Sciences Incubator documents checklist." },
    ],
    faq: lorealGreenFaq,
  },
  "csr-fund": {
    title: `CSR Fund | ${site.companyName}`,
    description: "CSR Fund — grant support of about Up to ₹2.63Cr for qualifying innovators and startups.",
    hero: {
      data: csrFundPage,
      images: { primary: photos.schemeVc, secondary: photos.schemeLab, circle: photos.schemeTech, secondaryAlt: "CSR Fund application support", circleAlt: "Founders preparing a CSR Fund proposal" },
      whatsappText: "Hi, I want to check eligibility for CSR Fund.",
    },
    unlock: { data: csrFundPage.unlock, image: { src: photos.schemeVc, alt: "CSR Fund grant support" } },
    sections: [
      { type: "services", data: csrFundPage.benefits, sectionId: "csrFund-benefits" },
      { type: "categories", data: csrFundPage.eligibility, sectionId: "csrFund-eligibility" },
      { type: "process", data: csrFundPage.process, sectionId: "csrFund-process" },
      { type: "documents", data: csrFundPage.documents, sectionId: "csrFund-documents", whatsappText: "Hi, please send me the CSR Fund documents checklist." },
    ],
    faq: csrFundFaq,
  },
  "cybersecurity-karnataka": {
    title: `Cybersecurity Incentive Policy Karnataka | ${site.companyName}`,
    description: "Cybersecurity Incentive Policy Karnataka — grant support of about Up to ₹50L for qualifying innovators and startups.",
    hero: {
      data: cybersecurityKarnatakaPage,
      images: { primary: photos.schemeLab, secondary: photos.schemeTech, circle: photos.schemeAgri, secondaryAlt: "Cybersecurity Incentive Policy Karnataka application support", circleAlt: "Founders preparing a Cybersecurity Incentive Policy Karnataka proposal" },
      whatsappText: "Hi, I want to check eligibility for Cybersecurity Incentive Policy Karnataka.",
    },
    unlock: { data: cybersecurityKarnatakaPage.unlock, image: { src: photos.schemeLab, alt: "Cybersecurity Incentive Policy Karnataka grant support" } },
    sections: [
      { type: "services", data: cybersecurityKarnatakaPage.benefits, sectionId: "cybersecurityKarnataka-benefits" },
      { type: "categories", data: cybersecurityKarnatakaPage.eligibility, sectionId: "cybersecurityKarnataka-eligibility" },
      { type: "process", data: cybersecurityKarnatakaPage.process, sectionId: "cybersecurityKarnataka-process" },
      { type: "documents", data: cybersecurityKarnatakaPage.documents, sectionId: "cybersecurityKarnataka-documents", whatsappText: "Hi, please send me the Cybersecurity Incentive Policy Karnataka documents checklist." },
    ],
    faq: cybersecurityKarnatakaFaq,
  },
  "early-stage-grant": {
    title: `Early-Stage Startup Grant | ${site.companyName}`,
    description: "Early-Stage Startup Grant — grant support of about ₹5L–₹1Cr for qualifying innovators and startups.",
    hero: {
      data: earlyStageGrantPage,
      images: { primary: photos.schemeTech, secondary: photos.schemeAgri, circle: photos.aboutServiceGrants, secondaryAlt: "Early-Stage Startup Grant application support", circleAlt: "Founders preparing a Early-Stage Startup Grant proposal" },
      whatsappText: "Hi, I want to check eligibility for Early-Stage Startup Grant.",
    },
    unlock: { data: earlyStageGrantPage.unlock, image: { src: photos.schemeTech, alt: "Early-Stage Startup Grant grant support" } },
    sections: [
      { type: "services", data: earlyStageGrantPage.benefits, sectionId: "earlyStageGrant-benefits" },
      { type: "categories", data: earlyStageGrantPage.eligibility, sectionId: "earlyStageGrant-eligibility" },
      { type: "process", data: earlyStageGrantPage.process, sectionId: "earlyStageGrant-process" },
      { type: "documents", data: earlyStageGrantPage.documents, sectionId: "earlyStageGrant-documents", whatsappText: "Hi, please send me the Early-Stage Startup Grant documents checklist." },
    ],
    faq: earlyStageGrantFaq,
  },
  "elevate-nxt": {
    title: `ELEVATE NxT | ${site.companyName}`,
    description: "ELEVATE NxT — grant support of about Up to ₹1Cr for qualifying innovators and startups.",
    hero: {
      data: elevateNxtPage,
      images: { primary: photos.schemeAgri, secondary: photos.aboutServiceGrants, circle: photos.schemeGuarantee, secondaryAlt: "ELEVATE NxT application support", circleAlt: "Founders preparing a ELEVATE NxT proposal" },
      whatsappText: "Hi, I want to check eligibility for ELEVATE NxT.",
    },
    unlock: { data: elevateNxtPage.unlock, image: { src: photos.schemeAgri, alt: "ELEVATE NxT grant support" } },
    sections: [
      { type: "services", data: elevateNxtPage.benefits, sectionId: "elevateNxt-benefits" },
      { type: "categories", data: elevateNxtPage.eligibility, sectionId: "elevateNxt-eligibility" },
      { type: "process", data: elevateNxtPage.process, sectionId: "elevateNxt-process" },
      { type: "documents", data: elevateNxtPage.documents, sectionId: "elevateNxt-documents", whatsappText: "Hi, please send me the ELEVATE NxT documents checklist." },
    ],
    faq: elevateNxtFaq,
  },
  "empowersphere": {
    title: `EmpowerSphere Skilling & Livelihood Futures | ${site.companyName}`,
    description: "EmpowerSphere Skilling & Livelihood Futures — grant support of about Up to ₹12.5L for qualifying innovators and startups.",
    hero: {
      data: empowerspherePage,
      images: { primary: photos.aboutServiceGrants, secondary: photos.schemeGuarantee, circle: photos.schemeSeed, secondaryAlt: "EmpowerSphere Skilling & Livelihood Futures application support", circleAlt: "Founders preparing a EmpowerSphere Skilling & Livelihood Futures proposal" },
      whatsappText: "Hi, I want to check eligibility for EmpowerSphere Skilling & Livelihood Futures.",
    },
    unlock: { data: empowerspherePage.unlock, image: { src: photos.aboutServiceGrants, alt: "EmpowerSphere Skilling & Livelihood Futures grant support" } },
    sections: [
      { type: "services", data: empowerspherePage.benefits, sectionId: "empowersphere-benefits" },
      { type: "categories", data: empowerspherePage.eligibility, sectionId: "empowersphere-eligibility" },
      { type: "process", data: empowerspherePage.process, sectionId: "empowersphere-process" },
      { type: "documents", data: empowerspherePage.documents, sectionId: "empowersphere-documents", whatsappText: "Hi, please send me the EmpowerSphere Skilling & Livelihood Futures documents checklist." },
    ],
    faq: empowersphereFaq,
  },
  "fintech-challenge": {
    title: `Fintech Startup Challenge | ${site.companyName}`,
    description: "Fintech Startup Challenge — grant support of about Challenge for qualifying innovators and startups.",
    hero: {
      data: fintechChallengePage,
      images: { primary: photos.schemeGuarantee, secondary: photos.schemeSeed, circle: photos.schemeStartup, secondaryAlt: "Fintech Startup Challenge application support", circleAlt: "Founders preparing a Fintech Startup Challenge proposal" },
      whatsappText: "Hi, I want to check eligibility for Fintech Startup Challenge.",
    },
    unlock: { data: fintechChallengePage.unlock, image: { src: photos.schemeGuarantee, alt: "Fintech Startup Challenge grant support" } },
    sections: [
      { type: "services", data: fintechChallengePage.benefits, sectionId: "fintechChallenge-benefits" },
      { type: "categories", data: fintechChallengePage.eligibility, sectionId: "fintechChallenge-eligibility" },
      { type: "process", data: fintechChallengePage.process, sectionId: "fintechChallenge-process" },
      { type: "documents", data: fintechChallengePage.documents, sectionId: "fintechChallenge-documents", whatsappText: "Hi, please send me the Fintech Startup Challenge documents checklist." },
    ],
    faq: fintechChallengeFaq,
  },
  "fund-sc-youth": {
    title: `Fund for SC Youth 2.0 | ${site.companyName}`,
    description: "Fund for SC Youth 2.0 — grant support of about Up to ₹30L for qualifying innovators and startups.",
    hero: {
      data: fundScYouthPage,
      images: { primary: photos.schemeSeed, secondary: photos.schemeStartup, circle: photos.schemePitch, secondaryAlt: "Fund for SC Youth 2.0 application support", circleAlt: "Founders preparing a Fund for SC Youth 2.0 proposal" },
      whatsappText: "Hi, I want to check eligibility for Fund for SC Youth 2.0.",
    },
    unlock: { data: fundScYouthPage.unlock, image: { src: photos.schemeSeed, alt: "Fund for SC Youth 2.0 grant support" } },
    sections: [
      { type: "services", data: fundScYouthPage.benefits, sectionId: "fundScYouth-benefits" },
      { type: "categories", data: fundScYouthPage.eligibility, sectionId: "fundScYouth-eligibility" },
      { type: "process", data: fundScYouthPage.process, sectionId: "fundScYouth-process" },
      { type: "documents", data: fundScYouthPage.documents, sectionId: "fundScYouth-documents", whatsappText: "Hi, please send me the Fund for SC Youth 2.0 documents checklist." },
    ],
    faq: fundScYouthFaq,
  },
  "fund-for-up": {
    title: `Fund for UP | ${site.companyName}`,
    description: "Fund for UP — grant support of about Up to ₹7.5L for qualifying innovators and startups.",
    hero: {
      data: fundForUpPage,
      images: { primary: photos.schemeStartup, secondary: photos.schemePitch, circle: photos.schemeVc, secondaryAlt: "Fund for UP application support", circleAlt: "Founders preparing a Fund for UP proposal" },
      whatsappText: "Hi, I want to check eligibility for Fund for UP.",
    },
    unlock: { data: fundForUpPage.unlock, image: { src: photos.schemeStartup, alt: "Fund for UP grant support" } },
    sections: [
      { type: "services", data: fundForUpPage.benefits, sectionId: "fundForUp-benefits" },
      { type: "categories", data: fundForUpPage.eligibility, sectionId: "fundForUp-eligibility" },
      { type: "process", data: fundForUpPage.process, sectionId: "fundForUp-process" },
      { type: "documents", data: fundForUpPage.documents, sectionId: "fundForUp-documents", whatsappText: "Hi, please send me the Fund for UP documents checklist." },
    ],
    faq: fundForUpFaq,
  },
};

export { SCHEME_CANONICAL_ALIASES };

desks["startup-india-seed-debt"] = desks["seed-fund"];
desks["horizon-fund-scheme"] = desks["horizon-fund"];
desks["venture-tech-funding"] = desks["venture-tech"];

export function getCanonicalSchemeSlug(slug: string) {
  return SCHEME_CANONICAL_ALIASES[slug] ?? slug;
}

export function getSchemeDesk(slug: string) {
  return desks[getCanonicalSchemeSlug(slug)] ?? desks[slug] ?? null;
}

export function getAllSchemeDeskSlugs() {
  return Object.keys(desks);
}

export function getIndexableSchemeSlugs() {
  return Object.keys(desks).filter((slug) => !SCHEME_CANONICAL_ALIASES[slug]);
}
